"use client";

import React from "react";
import Script from "next/script";

const PaymentPage = () => {
  const handlePayment = () => {
    if (!window.Razorpay) {
      alert("Razorpay is still loading. Please try again.");
      return;
    }

    const options = {
      key: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
      amount: 50000, // ₹500 in paise
      currency: "INR",
      name: "Supportly",
      description: "Support a creator",
      image: "https://example.com/your_logo.png",

      // Use an order ID generated by your backend.
      // Do not use a hardcoded sample order ID.
      order_id: "YOUR_SERVER_GENERATED_ORDER_ID",

      handler: function (response) {
        console.log("Payment response:", response);
        alert("Payment completed. Verify it on your server.");
      },

      prefill: {
        name: "",
        email: "",
        contact: "",
      },

      notes: {
        purpose: "Creator support",
      },

      theme: {
        color: "#6366f1",
      },
    };

    const razorpay = new window.Razorpay(options);

    razorpay.on("payment.failed", function (response) {
      console.error("Payment failed:", response.error);
      alert("Payment failed. Please try again.");
    });

    razorpay.open();


  };

  return (
    <> <Script
      src="https://checkout.razorpay.com/v1/checkout.js"
      strategy="lazyOnload"
    />


      < main className="flex min-h-screen items-center justify-center bg-slate-950" >
        <button
          onClick={handlePayment}
          className="rounded-lg bg-indigo-600 px-6 py-3 font-medium text-white hover:bg-indigo-500"
        >
          Pay ₹500
        </button>
      </main >
    </>


  );
};

export default PaymentPage;
